# Generated by Django 3.2.4 on 2021-06-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietApi', '0002_auto_20210629_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
